version: '3.9'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile

    ports:
      - '3000:3000'

    depends_on:
      - backend

  backend: 
    build: 
      context: ./api
      dockerfile: Dockerfile

    ports:
      - '8000:8000'