import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Container, Row, Col, Card, Button } from 'react-bootstrap';
import styles from '<kanbana-front>/styles/Home.module.css'
import NavBar from "<kanbana-front>/pages/component/navBar";
import AddPeople from "<kanbana-front>/pages/component/addPeople";

const inter = Inter({ subsets: ['latin'] })

export default function projectView() {
    return (
        <>
            <Head>
                <title>people</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar></NavBar>
            <main className={styles.main}>
                <AddPeople></AddPeople>
            </main>
        </>
    )
}
